#! /bin/sh

col0=#282a36
col1=#ff5555
col2=#50fa7b
col3=#f1fa8c
col4=#bd93f9
col5=#ff79c6
col6=#8be9fd
col7=#bfbfbf
col8=#4d4d4d
col9=#ff6e67
col10=#5af78e
col11=#f4f99d
col12=#caa9fa
col13=#ff92d0 
col14=#9aedfe
col15=#f8f8f2
colinac=#cb5852
colact=#8c3c38

####################################
###### Getting things started ######
####################################

# Arrange monitors and create desktops
setupmonitors

bspc monitor HDMI-A-0 -d I II III IV V
bspc monitor DisplayPort-1 -d VI VII VIII IX X

# Program startup routine
bspstart

# Set some colors 
bspc config normal_border_color "$colinac"
bspc config focused_border_color "$col2"
bspc config presel_feedback_color "$col3"

bspc config border_width         4
bspc config window_gap          20

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

## Window Rules
bspc rule -a Zathura state=tiled
bspc rule -a Transmission-gtk desktop=X
bspc rule -a qBittorrent desktop=X 
bspc rule -a TelegramDesktop state=tiled desktop=IX 
bspc rule -a Anki state=floating
bspc rule -a Pixinsight state=floating

# Scratchpad rules
bspc rule -a scterm sticky=on state=floating rectangle=710x360+1195+710 hidden=on
bspc rule -a scfm sticky=on state=floating rectangle=710x360+1195+410 hidden=on

## Launch scratchpad terminal if not already present
if [ -z "$(xdotool search --class scterm)" ];
then
	st -A 1 -c scterm
fi
# Same for scratchpad file manager
if [ -z "$(xdotool search --class scfm)" ];
then
	st -A 1 -c scfm -e ranger
fi

## Window swallowing
 pidof bspswallow || bspswallow &
