#! /bin/sh

col0=#2f2f44
col1=#a863ff
col2=#bc37ff
col3=#2864ff
col4=#e369ff
col5=#f02aff
col6=#ff487c
col7=#ffc9fd
col8=#5e4d5e
col9=#c992ff
col10=#c564ff
col11=#84a5ff
col12=#f1a2ff
col13=#ea96ff 
col14=#ff77a2
col15=#ffffff
colinac=#c081cb
colact=#84598c

####################################
###### Getting things started ######
####################################

# Arrange monitors and create desktops
if [ $(hostname) = "astro" ]; then
	setupmonitors
	bspc monitor HDMI-A-0 -d I II III IV V VI VII
	bspc monitor DisplayPort-1 -d  VIII IX X
elif [ $(hostname) = "EVA-01" ]; then
	bspc monitor -d I II III IV V VI VII VIII IX X
fi

# Program startup routine
bspstart

# Set some colors 
bspc config normal_border_color "$colinac"
bspc config focused_border_color "$col2"
bspc config presel_feedback_color "$col3"

bspc config border_width         4
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

## Window Rules
bspc rule -a Zathura state=tiled
bspc rule -a Transmission-gtk desktop=X
bspc rule -a qBittorrent desktop=X 
bspc rule -a TelegramDesktop state=floating desktop=IX 
bspc rule -a Anki state=floating
bspc rule -a Pixinsight state=floating
bspc rule -a Gimp state=floating
bspc rule -a subs2srs state=floating rectangle=1038x865+398+106

# Scratchpad rules
bspc rule -a scterm sticky=on state=floating rectangle=710x360+1195+710 hidden=on
bspc rule -a scfm sticky=on state=floating rectangle=710x360+1195+410 hidden=on

## Launch scratchpad terminal if not already present
if [ -z "$(xdotool search --class scterm)" ];
then
	alacritty --class alacritty,scterm &
fi
# Same for scratchpad file manager
if [ -z "$(xdotool search --class scfm)" ];
then
	alacritty --class alacritty,scfm -e ranger &
fi

## Window swallowing
pidof bspswallow || bspswallow &
