#! /bin/sh

col0=#312d36
col1=#ff3144
col2=#ff5966
col3=#5797ff
col4=#859aff
col5=#e398ff
col6=#9dbdff
col7=#c9d9ff
col8=#676f7f
col9=#ff5464
col10=#ff5e6a
col11=#92bbff
col12=#a1b0ff
col13=#ebb3ff 
col14=#b7ceff
col15=#e4ecff
colinac=#7495cb
colact=#50668c

####################################
###### Getting things started ######
####################################

# Arrange monitors and create desktops
if [ $(hostname) = "astro" ]; then
	setupmonitors
	bspc monitor HDMI-A-0 -d I II III IV V VI VII
	bspc monitor DisplayPort-1 -d  VIII IX X
elif [ $(hostname) = "EVA-01" ]; then
	bspc monitor -d I II III IV V VI VII VIII IX X
fi

# Program startup routine
pidof sxhkd || sxhkd -c $HOME/.config/sxhkd/sxhkdrc.common $HOME/.config/sxhkd/sxhkdrc.desk &
bspstart

# Set some colors 
bspc config normal_border_color "$colinac"
bspc config focused_border_color "$col2"
bspc config presel_feedback_color "$col3"

bspc config border_width         4
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

## Window Rules
bspc rule -a Zathura state=tiled
bspc rule -a Transmission-gtk desktop=X
bspc rule -a qBittorrent desktop=X 
bspc rule -a TelegramDesktop state=floating desktop=IX 
bspc rule -a Anki state=floating
bspc rule -a Pixinsight state=floating
bspc rule -a Gimp state=floating
bspc rule -a subs2srs state=floating rectangle=1038x865+398+106

# Scratchpad rules
bspc rule -a scterm sticky=on state=floating rectangle=710x360+1195+710 hidden=on
bspc rule -a scfm sticky=on state=floating rectangle=710x360+1195+410 hidden=on

## Launch scratchpad terminal if not already present
if [ -z "$(xdotool search --class scterm)" ];
then
	$TERM --class scterm
fi
# Same for scratchpad file manager
if [ -z "$(xdotool search --class scfm)" ];
then
	$TERM --class scfm -e ranger
fi

## Window swallowing
pidof bspswallow || bspswallow &
